config/routes.rb
Rails.application.routes.draw do

  devise_scope :usuario do
    get 'sign_out' => 'devise/sessions#destroy'
    get 'salir' => 'devise/sessions#destroy',
      as: :terminar_sesion

    post 'usuarios/iniciar_sesion', to: 'devise/sessions#create'
    get 'usuarios/iniciar_sesion', to: 'devise/sessions#new',
      as: :iniciar_sesion


    # El siguiente para superar mala generación del action en el formulario
    # cuando se autentica mal (genera 
    # /mujeresindigenas/sivel2/mujeresindigenas/sivel2/usuarios/sign_in )
    if (Rails.configuration.relative_url_root != '/') 
      ruta = File.join(Rails.configuration.relative_url_root, 'usuarios/sign_in')
      post ruta, to: 'devise/sessions#create'
    end
  end
  devise_for :usuarios, :skip => [:registrations], module: :devise
  as :usuario do
    get 'usuarios/edit' => 'devise/registrations#edit', 
      :as => 'editar_registro_usuario'    
    put 'usuarios/:id' => 'devise/registrations#update', 
      :as => 'registro_usuario'            
  end
  resources :usuarios, path_names: { new: 'nuevo', edit: 'edita' } 


  # De sivel2_sjr

  get '/casos/lista' => 'sivel2_sjr/casos#lista'
  get '/casos/mapaosm' => 'sivel2_sjr/casos#mapaosm'
  get '/casos/nuevaubicacion' => 'sivel2_sjr/casos#nueva_ubicacion'
  get '/casos/nuevavictima' => 'sivel2_sjr/casos#nueva_victima'
  get '/casos/nuevopresponsable' => 'sivel2_sjr/casos#nuevo_presponsable'
  get '/casos/busca' => 'sivel2_sjr/casos#busca'
  get '/casos/filtro' => 'sivel2_sjr/casos#index', as: :casos_filtro
  post '/casos/filtro' => 'sivel2_sjr/casos#index', as: :envia_casos_filtro

  get '/conteos/personas' => 'sivel2_sjr/conteos#personas', as: :conteos_personas
  post "/conteos/personas" => 'sivel2_sjr/conteos#personas', as: :post_conteos_personas
  get '/conteos/respuestas' => 'sivel2_sjr/conteos#respuestas', as: :conteos_respuestas

  get '/desplazamientos/nuevo' => 'sivel2_sjr/desplazamientos#nuevo'

  get '/respuestas/nuevo' => 'sivel2_sjr/respuestas#nuevo'

  #  get '/victimas' => 'victimas#index', as: :victimas
  #  get '/victimas/nuevo' => 'victimas#nuevo'
  get '/victimascolectivas/nuevo' => 'sivel2_sjr/victimascolectivas#nuevo'

  get "/api/sivel2sjr/poblacion_sexo_rangoedadac" => 'sivel2_sjr/casos#poblacion_sexo_rangoedadac',
    as: :sivel2sjr_poblacion_sexo_rangoedadac

  resources :casos, path_names: { new: 'nuevo', edit: 'edita' }, 
    controller: 'sivel2_sjr/casos'

  # Fin de sivel2_sjr

  get "/bitacora7z" => 'msip/bitacora7z#new', as: 'bitacora7z'
  post "/bitacora7z" => 'msip/bitacora7z#create'
  namespace :admin do
    ab = ::Ability.new
    ab.tablasbasicas.each do |t|
      if (t[0] == "") 
        c = t[1].pluralize
        resources c.to_sym, 
          path_names: { new: 'nueva', edit: 'edita' }
      end
    end
  end

  root 'msip/hogar#index'
  get '/eventos/nuevo' => 'eventos#nuevo'  


  mount Jos19::Engine, at: "/", as: 'jos19'
  mount Sivel2Gen::Engine, at: "/", as: 'sivel2_gen'
  mount Cor1440Gen::Engine, at: "/", as: 'cor1440_gen'
  mount Mr519Gen::Engine, at: "/", as: 'mr519_gen'
  mount Heb412Gen::Engine, at: "/", as: 'heb412_gen'
  mount Msip::Engine, at: "/", as: 'msip'

end

app/views/layouts/application.html.erb
<% content_for :titulo do %>
    <%= Msip.titulo %>
<% end %>


<% content_for :menu do %>
  <%= grupo_menus do %>
    <% if !current_usuario.nil? %>
        <%= despliega_abajo "Casos" do %>
          <%= opcion_menu "Listado", sivel2_gen.casos_path,
            desplegable: true %>
          <%= opcion_menu "Nuevo", sivel2_gen.new_caso_path,
            desplegable: true %>
          <%= opcion_menu "Conteo Demografía Víctimas", 
            sivel2_gen.conteos_personas_path,
            desplegable: true %>
          <!-- %= opcion_menu "Validaciones", sivel2_gen.validarcasos_path %-->
        <% end %>
    <% end %>
  <% end %>
  <%= grupo_menus :pull => :right do %>
    <%= despliega_abajo "Documentos" do %>
      <%= opcion_menu "Manual", 
        File.join(Rails.configuration.relative_url_root, 'doc/index.html'),
        desplegable: true %>
      <% if can?(:read,Heb412Gen::Doc) %>
        <%= opcion_menu "Plantillas", heb412_gen.sisini_path,
          desplegable: true %>
      <% end %>
    <% end %>
    <% if !current_usuario.nil? %>
      <%= despliega_abajo "Administrar" do %>
        <%= opcion_menu "Clave y tema", main_app.editar_registro_usuario_path,
          desplegable: true %>
        <% if session[:capturacaso_acordeon] %>
          <%= opcion_menu 'Ficha caso vertical ✓', 
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical' 
          %>
        <% else %>
          <%= opcion_menu 'Ficha caso vertical', 
            sivel2_gen.fichacasovertical_path,
            desplegable: true, id: 'fichacasovertical' 
          %>
        <% end %>
        <% if can? :manage, ::Usuario %>
          <%= opcion_menu "Usuarios", main_app.usuarios_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, :tablasbasicas %>
          <%= opcion_menu "Tablas Básicas", sivel2_gen.tablasbasicas_path,
            desplegable: true %>
        <% end %>
        <%= opcion_menu "Árbol de presuntos responsables",
          sivel2_gen.arbol_presponsables_path, desplegable: true %>
        <% if can? :manage, Msip::Respaldo7z %>
          <%= opcion_menu "Respaldo cifrado", msip.respaldo7z_path,
            desplegable: true %>
          <%= opcion_menu "Bitácora cifrada", main_app.bitacora7z_path,
            desplegable: true %>
        <% end %>
        <% if can? :manage, Heb412Gen::Doc %>
          <%= opcion_menu "Asociar plantilla a listado de casos", 
            heb412_gen.new_plantillahcm_path,
            desplegable: true %>
        <% end %>
      <% end %>
      <%= opcion_menu "Salir #{current_usuario.nusuario}", 
        main_app.terminar_sesion_path %>
    <% else %>
      <%= opcion_menu "Acerca de", sivel2_gen.acercade_path %>
      <%= opcion_menu "Iniciar Sesión", main_app.iniciar_sesion_path %> 
    <% end %>
  <% end %>
<% end %> 

<% content_for :piedepagina do %>
  <p><span class='derechos'>
    Sistema de información de <a href="https://github.com/pasosdeJesus/sivel2_mujeresindigenas">código abierto</a>, desarrollado para CODACOP, ONIC, OIK y ACIN por <a href="http://www.pasosdeJesus.org" target="_blank">Pasos de Jesús</a>. <%= Date.today.year %>.
    </span></p>
<% end %>

<%= render template: "layouts/msip/application" %>